version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: CMAKE_BUILD_TIMEOUT
      variableValue: "36000"
    - type: EnvironmentVariable
      variableName: CMAKE_BUILD_OUTPUT_TIMEOUT
      variableValue: "3600"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"
  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
